@echo off

@rem  This script validates a few sample OData responses against the JSON Schema files generated by transform.cmd
rem
@rem  Prerequisites
@rem  - ajv-cli is installed - npm install -g ajv-cli

call ajv validate -s json-schema-draft-07.json -d odata-meta-schema.json

call ajv validate -s ..\examples\csdl-16.1.schema.json -d ..\examples\csdl-16.1-Categories.json -m odata-meta-schema.json --unknown-formats=int32 --unknown-formats=decimal

call ajv validate -s ..\examples\csdl-16.1.schema.json -d ..\examples\csdl-16.1-Categories-empty.json -m odata-meta-schema.json --unknown-formats=int32 --unknown-formats=decimal

call ajv test --invalid -s ..\examples\csdl-16.1.schema.json -d ..\examples\csdl-16.1-Categories-fail.json -m odata-meta-schema.json --unknown-formats=int32 --unknown-formats=decimal > nul
if %ERRORLEVEL% == 0 (
  echo ..\examples\csdl-16.1-Categories-fail.json invalid as expected
) else (
  echo !!! validation should have failed !!!
)

call ajv validate -s ..\examples\csdl-16.1.schema.json -d ..\examples\csdl-16.1-Category.json -m odata-meta-schema.json --unknown-formats=int32 --unknown-formats=decimal

call ajv validate -s ..\examples\csdl-16.1.schema.json -d ..\examples\csdl-16.1-Category-projected.json -m odata-meta-schema.json --unknown-formats=int32 --unknown-formats=decimal

call ajv test --invalid -s ..\examples\csdl-16.1.schema.json -d ..\examples\csdl-16.1-Category-fail.json -m odata-meta-schema.json --unknown-formats=int32 --unknown-formats=decimal > nul
if %ERRORLEVEL% == 0 (
  echo ..\examples\csdl-16.1-Category-fail.json invalid as expected
) else (
  echo !!! validation should have failed !!!
)

call ajv validate -s ..\examples\csdl-16.1.schema.json -d ..\examples\csdl-16.1-MainSupplier.json -m odata-meta-schema.json --unknown-formats=int32 --unknown-formats=decimal

call ajv validate -s ..\examples\csdl-16.1.schema.json -d ..\examples\csdl-16.1-Product.json -m odata-meta-schema.json --unknown-formats=int32 --unknown-formats=decimal

call ajv validate -s ..\examples\miscellaneous-PrimitiveTypes-wrapperschema.json -d ..\examples\miscellaneous-PrimitiveTypes.json -r ..\examples\miscellaneous.schema.json -m odata-meta-schema.json --unknown-formats=int32 --unknown-formats=decimal --unknown-formats=base64url --unknown-formats=double --unknown-formats=single --unknown-formats=duration --unknown-formats=int64